openapi: 3.2.0
info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
  title: B2X-Global-SiteManagement-API-v1 Retrieve Geographic Site…
  description: '**This file forms part of MEF 122**


    This API implements Business Requirements described in MEF 79


    It allows to retrieve a list of Geographic Sites and to get all

    information for one geographic site.'
servers:
- url: https://api-garden.teliacompany.com/v1/api/mef/geographicSiteManagement
  description: Production
- url: https://api-garden-test.teliacompany.com/v1/api/mef/geographicSiteManagement
  description: Test
- url: https://api-garden.teliacompany.com/sandbox/v1/api/mef/geographicSiteManagement
  description: Sandbox
security:
- prodBearerAuth: []
- testBearerAuth: []
tags:
- name: retrieveGeographicSite
  description: Retrieves detailed information for a specific geographic site using its ID.
paths:
  /{country}/geographicSite/{id}:
    get:
      operationId: retrieveGeographicSite
      summary: Retrieve geographic site by ID
      description: Retrieves detailed information for a specific geographic site using its ID.
      tags:
      - retrieveGeographicSite
      parameters:
      - name: country
        in: path
        required: true
        description: Country selector for the address operation.
        schema:
          type: string
          enum:
          - se
          - fi
          - global
        examples:
          Sweden:
            summary: Sweden
            value: se
          Finland:
            summary: Finland
            value: fi
          Global:
            summary: Global
            value: global
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Unique identifier of the geographic site.
      responses:
        '200':
          description: Successful retrieval of a site
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeographicSite'
              examples:
                GetSiteById:
                  summary: Get Site Sweden by ID
                  value:
                    id: 105839411
                    siteCompanyName: Telia
                    additionnalSiteInformation: '{"siteId":"N229 NTP 001","category":"OnNet"}'
                    status: EXISTING
                    fieldedAddress:
                      id: 105839411
                      streetNr: '10'
                      streetName: KRISTINAGATAN
                      postcode: '60226'
                      city: NORRKÖPING
                      stateOrProvince: ÖSTERGÖTLANDS LÄN
                      country: SE
                    geographicLocation:
                      id: 105839411
                      spatialRef: WGS84
                      geographicPoint:
                      - latitude: '58.591864'
                        longitude: '16.190793'
                    geographicSubAdress:
                    - id: 105839411
                      buildingName: '161614704'
                      subUnit:
                      - subUnitType: business
                        subUnitIdentifier: '1302'
                    - id: 105839411
                      buildingName: '161304865'
                      subUnit:
                      - subUnitType: flat
                        subUnitIdentifier: 1581110-2001
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
              examples:
                BadRequestExample:
                  summary: Example bad request error
                  value:
                    code: '400'
                    reason: Bad Request
                    message: Mandatory field siteId is missing from path parameters
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
              examples:
                UnauthorizedExample:
                  summary: Example unauthorized error
                  value:
                    code: '401'
                    reason: Unauthorized
                    message: Error while authenticating TMF
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
              examples:
                NotFoundExample:
                  summary: Example not found error
                  value:
                    code: '404'
                    reason: Not Found
                    message: Site not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500'
              examples:
                InternalServerErrorExample:
                  summary: Example internal server error
                  value:
                    code: '500'
                    reason: Internal Server Error
                    message: Error occurred while calling the API
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error503'
              examples:
                ServiceUnavailableExample:
                  summary: Example service unavailable error
                  value:
                    code: '503'
                    reason: Service Unavailable
                    message: Service Unavailable
components:
  schemas:
    GeographicLocation:
      type: object
      properties:
        id:
          type: integer
        spatialRef:
          type: string
        geographicPoint:
          type: array
          items:
            $ref: '#/components/schemas/GeographicPoint'
      required:
      - id
      - spatialRef
      - geographicPoint
      additionalProperties: false
    GeographicSubAdress:
      type: object
      properties:
        id:
          type: integer
        buildingName:
          type: string
        levelType:
          type: string
        levelNumber:
          type: string
        subUnit:
          type: array
          items:
            $ref: '#/components/schemas/SubUnit'
      required:
      - id
      - buildingName
      - subUnit
      additionalProperties: false
    Error401:
      type: object
      properties:
        code:
          type: string
          example: '401'
        reason:
          type: string
          example: Unauthorized
        message:
          type: string
          example: Error while authenticating TMF
      required:
      - code
      - reason
    Error404:
      type: object
      properties:
        code:
          type: string
          example: '404'
        reason:
          type: string
          example: Not Found
        message:
          type: string
          example: Site not found
      required:
      - code
      - reason
    SubUnit:
      type: object
      properties:
        subUnitType:
          type: string
        subUnitIdentifier:
          type:
          - string
          - 'null'
      required:
      - subUnitType
      additionalProperties: false
    Error400:
      type: object
      properties:
        code:
          type: string
          example: '400'
        reason:
          type: string
          example: Bad Request
        message:
          type: string
          example: Mandatory field siteId is missing from path parameters
      required:
      - code
      - reason
    Error500:
      type: object
      properties:
        code:
          type: string
          example: '500'
        reason:
          type: string
          example: Internal Server Error
        message:
          type: string
          example: Error occurred while calling the API
      required:
      - code
      - reason
    Error503:
      type: object
      properties:
        code:
          type: string
          example: '503'
        reason:
          type: string
          example: Service Unavailable
        message:
          type: string
          example: Service Unavailable
      required:
      - code
      - reason
    GeographicSite:
      type: object
      properties:
        id:
          type: integer
          example: 105839411
        siteCompanyName:
          type: string
          example: Telia
        additionnalSiteInformation:
          type: string
          example: '{"siteId":"N229 NTP 001","category":"OnNet"}'
        status:
          type: string
          example: EXISTING
        fieldedAddress:
          $ref: '#/components/schemas/FieldedAddress'
        geographicLocation:
          $ref: '#/components/schemas/GeographicLocation'
        geographicSubAdress:
          type: array
          items:
            $ref: '#/components/schemas/GeographicSubAdress'
      required:
      - id
      - siteCompanyName
      - additionnalSiteInformation
      - status
      - fieldedAddress
      - geographicLocation
      - geographicSubAdress
      additionalProperties: false
    Error403:
      type: object
      properties:
        code:
          type: string
          example: '403'
        reason:
          type: string
          example: Forbidden
        message:
          type: string
          example: Access to the requested resource is denied
      required:
      - code
      - reason
    FieldedAddress:
      type: object
      properties:
        id:
          type: integer
        streetNr:
          type: string
        streetName:
          type: string
        postcode:
          type: string
        city:
          type: string
        stateOrProvince:
          type: string
        country:
          type: string
      required:
      - id
      - streetNr
      - streetName
      - postcode
      - city
      - stateOrProvince
      - country
      additionalProperties: false
    GeographicPoint:
      type: object
      properties:
        latitude:
          type: string
        longitude:
          type: string
      required:
      - latitude
      - longitude
      additionalProperties: false
  securitySchemes:
    prodBearerAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api-garden.teliacompany.com/v4/oauth/client_credential/accesstoken
          scopes: {}
      description: Token endpoint for the production environment
    testBearerAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api-garden-test.teliacompany.com/v4/oauth/client_credential/accesstoken
          scopes: {}
      description: Token endpoint for all test environments
x-project-id: B2X-Global-SiteManagement-API-v1
